/**
 * DONE: REALIZAR QUERY SOLO CON COLUMNAS NECESARIAS.
 * DONE: QUITAR PERIODICIDAD DEL CODIGO, ESTRÉS SOLO PARA EL PROGRAMADOR DE TAREAS.
 * DONE: VALIDAR DATOS NULL.
 * * TIEMPO PROMEDIO EN PROCESAR UN PEDIDO:
 * * PEDIDO INSERTADO PUEDE QUEDAR EN DOS ESTADOS (ORDEN, PRELIMINAR).
 * * PEDIDO RECIBIDO PUEDE QUEDAR EN DOS ESTADOS (ERROR O INSERTADO).
 * TODO: PERDURAR EL ARCHIVO TEMPORAL DURANTE TODO EL DIA CON REGISTROS DE PEDIDOS EXITOSOS Y NO EXITOSOS.
 * TODO: HACER EJECUCIÓN EN SEGUNDO PLANO.
 * TODO: INVESTIGACIÓN DE PRECIOS PARA PODER SUSTENTAR LA PROPUESTA.
 * TODO: DOCUMENTACIÓN META Y TWILIO.
 * TODO: GENERAR LA PLANTILLA DEPENDIENDO DEL DISTRIBUIDOR Y DEL COORDINADOR (DISTRIBUIDORA TAL, SE HA INSERTADO EL PEDIDO TAL A SAP, A LA HORA POR UN MONTO DE TAL VALOR BRUTO DE TAL).
 * TODO: INCLUIR EN EL ARCHIVO TEMPORAL LA TRAZABILIDAD DE ES ENVIADO.
 * TODO: INFORMAR SOBRE EL VALOR BRUTO Y EL VALOR TOTAL.
 * TODO: INFORMAR SOBRE LA ZONA O EK TERRITORIO CORRESPONDIENTE A LA EDS.
 * TODO: HACER CONEXIÓN A LA DB.
 */
