/**
 * TODO: Generar periocidad en horario laboral, cada 15 minutos & filtrar por solo clientes que lo necesiten.
 * TODO: Investigacion de precios para poder sustentar la propuesta.
 * DONE: REALIZAR QUERY SOLO CON SOLUMNAS NECESARIAS
 * DONE: QUITAR PERIOCIDAD DEL CODIGO, ESTRESS SOLO PARA EL PROGRAMADOR DE TAREAS
 * DONE: VALIDAR DATOS NULL
 */
//* TIEMPO PROMEDIO EN PROCESAR UN PEDIDO: 
// TODO: PERDURAR EL ARCHIVO TEMPORAL DURANTE TODO EL DIA CON REGISTROS DE PEDIDOS EXITOSOS Y NO EXITOSOS
// TODO: HACER EJECUCIÓN EN SEGUNDO PLANO
